### PR TITLE
use AC_SUBST vars

### PR DESCRIPTION
**Pull request by kiwiroy**
A patch for the _minor_ changes required to install iptools on OS X (yosemite) with a macports install of libboost. It uses a different library names for the multi-thread version (libboost_*-mt) which I have installed.
### Mac OS X

``` bash
% sw_vers
ProductName:       Mac OS X
ProductVersion: 10.10.5
BuildVersion:   14F27
```
### R

``` bash
% R -e ’sessionInfo()'
> sessionInfo()
R version 3.1.3 (2015-03-09)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.10.5 (Yosemite)

locale:
[1] C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     
```
### Macports

``` bash
% port version
Version: 2.3.4

% port installed boost
The following ports are currently installed:
  boost @1.59.0_2+no_single+no_static+python27 (active)

% ls /opt/local/lib/libboost_{system,regex}*.dylib
/opt/local/lib/libboost_regex-mt.dylib     /opt/local/lib/libboost_system-mt.dylib
```
### Error

``` R
install.packages(‘iptools’, type=’source')
<snip>
clang++ -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o iptools.so RcppExports.o asio_bindings.o iptools.o -L/opt/local/lib -lboost_system -lboost_regex -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
ld: library not found for -lboost_system
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [iptools.so] Error 1
ERROR: compilation failed for package ‘iptools’
* removing ‘/Users/hrards/Library/R/3.1/library/iptools’
```
### Resolved

``` R
devtools::install_github("kiwiroy/iptools", ref="f/configure-fix”)
<snip>
clang++ -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o iptools.so RcppExports.o asio_bindings.o iptools.o -L/opt/local/lib -lboost_system-mt -lboost_regex-mt -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
installing to /Users/hrards/Library/R/3.1/library/iptools/libs
** R
** data
** inst
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (iptools)
```

[Review on Reviewable](https://reviewable.io/reviews/cran/iptools/1)

### CODE REVIEW

**Comment by kiwiroy** [comment]
@hrbrmstr hope that captures everything.

**Comment by hrbrmstr** [comment]
#ty. I'll try for a CRAN push on this next week. PR is very much appreciated.

**Comment by hrbrmstr** [comment]
(I'll also move it to my gh repo since this is just an unofficial CRAN mirror)

**Comment by kiwiroy** [comment]
@hrbrmstr ah, that all makes a lot more sense now... sorry, I completely missed your gh repo! e427729  makes better reference to hrbrmstr/iptools@e061323

**Comment by gaborcsardi** [comment]
Hi, thanks for the PR! This is a read-only mirror of CRAN, so please send your changes to the original package authors. See the `DESCRIPTION` file.

Thanks!

**Pull request closed without merging**
